var/lib/pulse2/clients/win/downloads/python-3.11.7-amd64.exe
var/lib/pulse2/clients/win/downloads/python_modules/pywin32-223.win32-py3.6.exe
var/lib/pulse2/clients/win/downloads/python_modules/pywin32-223.win-amd64-py3.6.exe
var/lib/pulse2/clients/win/downloads/python_modules/PyQt6-6.6.1-cp38-abi3-win_amd64.whl
var/lib/pulse2/clients/win/downloads/python_modules/PyQt6_Qt6-6.6.1-py3-none-win_amd64.whl
var/lib/pulse2/clients/win/downloads/python_modules/sip-6.8.2-py3-none-any.whl
var/lib/pulse2/clients/win/downloads/python_modules/tray-0.1.0.tar.gz
